### ISSUE TITLE
docker files

### ISSUE THREAD

**Issue by nedelec** [flatironinstitute/aLENS#9]
I think your method is very interesting, and I would like to run my own benchmarks. 

Your "Author Response" which is visible on eLife.com says "We have also packaged the precompiled executable as a Docker image, freely available on Docker Hub (https://hub.docker.com/r/wenyan4work/alens), so that any interested users can run aLENS on any operating system, without compilation." 

However, on https://hub.docker.com/r/wenyan4work/alens/tags, I only see one architecture "linux/amd64".
I am interested in running on the MacOS 12.6, Apple Silicon (ARM64) architecture. 
Could you provide this or clarify the situation?
Thank you!

**Comment by blackwer** [comment]
I can see if I can get the docker image working on an M1 later. I'm not
sure what kind of performance to expect, but I know the original author
worked mostly on optimizing things for intel architectures (arm wasn't so
much a thing yet). I also assume that it'd use Rosetta translation, hurting more.
Sadly Wen has left the FI, so support is more limited
now -- though we are currently hiring a new primary developer (or two) for
the project.

The software was certainly designed with linux in mind, since it was built
for HPC centers - hence the heavy dependencies. This does make mac support
very difficult, as they are constantly breaking support for various
software packages we rely on -- they don't even have a native openmp
compiler, which is integral for this code. That said, I'll give a "best
effort" push to get this working somehow. If it's proving to be too
burdensome, do you have access to some linux resources that you could
benchmark on?

**Comment by wenyan4work** [comment]
Docker on m1 can run x86 images using m1’s x86 compatibility mode.
Compiling a m1 native version is not worth the hassle because the heavy
dependencies have limited support for arm.

In addition, the docker images were provided for convenience, not for
benchmarking purposes.

**Comment by nedelec** [comment]
Thanks for looking into this. For OpenMP support, you can use GNU's gcc. Apple's clang compiler also has OpenMP support (-Xclang -fopenmp)... it is disabled by default, but usable. 
I will have to do the benchmarking with whatever I am able to run...

**Comment by blackwer** [comment]
Are you able to use the docker image as is?

**Comment by nedelec** [comment]
I have a Docker app running, and it works with some 'tutorial', but I get this error:
> docker pull wenyan4work/alens:latest
Error response from daemon: manifest for wenyan4work/alens:latest not found: manifest unknown: manifest unknown

**Comment by blackwer** [comment]
with this? shouldn't need the :latest tag
docker pull wenyan4work/alens


On Wed, Nov 2, 2022 at 12:00 PM F. Nedelec ***@***.***> wrote:
>
> I have a Docker app running, and it works with some 'tutorial', but I get
this error:
>
> docker pull wenyan4work/alens:latest
> Error response from daemon: manifest for wenyan4work/alens:latest not
found: manifest unknown: manifest unknown
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID:
***@***.***>

**Comment by nedelec** [comment]
makes no difference:
> docker pull wenyan4work/alens
> Using default tag: latest
> Error response from daemon: manifest for wenyan4work/alens:latest not found: manifest unknown: manifest unknown

**Comment by blackwer** [comment]
Oops. Sorry. This is what you want (from the tags page)
docker pull wenyan4work/alens:gcc11_trilinos12

**Comment by nedelec** [comment]
This seem to work better... now it is downloading. I was just copy-pasting the pull command from:
https://hub.docker.com/r/wenyan4work/alens

**Comment by nedelec** [comment]
It says 'admiring_banzai' and it is running with a warning that performance may be poor, since it is running in emulator.
CPU usage 0%, Memory = 14.6 MB
What is it supposed to do?

**Comment by blackwer** [comment]
Apologies. There is a more recent version under adam's dockerhub, as he is
now the primary maintainer. You might get better support there.
https://lamsoa729-alens.readthedocs.io/en/latest/quickstart.html

Re: performance warning
I'm not sure what it's supposed to do, but the performance warning makes
sense. You have to emulate intel instructions on the M1, which is
reasonably fast, but not great. I don't actually use or maintain the
software -- just assist in builds and some design decisions, so I can only
really get you as far as getting the docker images working and not much
beyond that.

Robert

**Comment by nedelec** [comment]
I could download lamsoa729/alens:latest, but I get an error:

# ./aLENS.X
qemu: uncaught target signal 4 (Illegal instruction) - core dumped
Illegal instruction

From my experience, this could be caused by Intel's AVX instructions, that are not emulated. SSE would work. Are you using AVX?

**Comment by blackwer** [comment]
Ah. Yeah it's likely Adam built that with AVX instructions. I'll look into
a native build or at least a docker image with standard x86_64 instructions
when I get a chance. This might take some time, since I have some other
priorities right now. Are you using brew or macports or ...?

**Comment by nedelec** [comment]
I was running the docker image, so no need of brew. Yes, it is using AVX.

**Comment by lamsoa729** [comment]
I just pushed a new docker image to [dockerhub](https://hub.docker.com/r/lamsoa729/alens) that should be using standard x86-64 instructions. Please try pulling this image with
`docker pull lamsoa729/alens`
and see if aLENS runs properly.

**Comment by lamsoa729** [comment]
@nedelec Have you been able to run the code using the new docker image?

**Comment by nedelec** [comment]
not yet. I am stuck in a series of deadlines.

**Comment by nedelec** [comment]
I got the new image (lamsoa729/alens)
```
# ls
Run  aLENS  local
# cd Run
# cp -r ../aLENS/Examples/MixMotorSliding .
# cd MixMotorSliding
# cp -r ~/aLENS/Run/* .
# ls
ProteinConfig.yaml  ProteinInitial.dat  README.md  RunConfig.yaml  TubuleInitial.dat  result  scripts
# ./aLENS.X
/bin/sh: 35: ./aLENS.X: not found
```

**Comment by lamsoa729** [comment]
Apologies. The `aLENS.X` executable was not automatically installed to `~/aLENS/Run` after the rebuild. During my tests I was copying `aLENS.X` from the build directory to my run folders manually. However, this was not being stored in the image.

You could rebuild the executable by going into `~/aLENS/build/` and running `make -j`. Then you could copy over the new `aLENS.X` to `~/Run/MixMotorSliding`. However, I've pushed yet another image where `aLENS.X` is properly installed in `~/aLENS/Run`.

**Comment by nedelec** [comment]
Thank you, it is running now! For some reason the terminal output disappeared, but that is maybe some other problem. Anyhow, how long should it take normally to run 'MixMotorSliding'?
<img width="266" alt="Screen Shot 2022-11-10 at 20 46 44" src="https://user-images.githubusercontent.com/21315875/201202924-4f386db8-99b1-47d8-8218-8fa9fe14fe58.png">

**Comment by nedelec** [comment]
It seems the program completed after 2h, and now I have many files... and I am not sure what to do with them...
I would love to get an image of the system, but there is nothing in your quick-start concerning this matter. 

I try my luck but:

    # ./MovieGen.sh
    MixMotorSliding_PNG
    ./MovieGen.sh: line 17: ffmpeg: command not found

**Comment by lamsoa729** [comment]
We use paraview to visualize the data. It uses the .vtk files to generate the pngs used by ./MovieGen.sh. That script just stitches the image together into a movie using ffmpeg. I will write up a quick tutorial on that tomorrow.

**Comment by lamsoa729** [comment]
> For some reason the terminal output disappeared, but that is maybe some other problem.

I have never encountered this problem before. My best guess is that it has something to do with dockers interaction with the terminal.

> Anyhow, how long should it take normally to run 'MixMotorSliding'?

I have not tested MixMotorSliding for speed but two hours seems slow. 'MixMotorSliding' is a simple example to show how  motors behave between two filaments. Our timing tests are performed on simulations with much greater numbers of objects (10^5-10^6 objects). Smaller simulations like MixMotorSliding do not take advantage of our collision solver or inherent parallelism. If you would like, I could send you the configuration files for these larger systems to test against.

**Comment by lamsoa729** [comment]
> We use paraview to visualize the data. It uses the .vtk files to generate the pngs used by ./MovieGen.sh. That script just stitches the image together into a movie using ffmpeg. I will write up a quick tutorial on that tomorrow.

I should also mention that in main README.md under Data organization section, there is an overview of the data files generated by an aLENS run. This will be covered in the new tutorial, but if you have experience with Paraview or VTK, you could generate images using this.

**Comment by lamsoa729** [comment]
>We use paraview to visualize the data. It uses the .vtk files to generate the pngs used by ./MovieGen.sh. That script just stitches the image together into a movie using ffmpeg. I will write up a quick tutorial on that tomorrow.

@nedelec The tutorial is up online https://lamsoa729-alens.readthedocs.io/en/latest/visualization.html. This requires you to pull a new docker image or pull the latest main branch inside your current docker container since I added a ParaView state (MixMotorSliding.pvsm) file to the `~/aLENS/Example/MixMotorSliding` folder so you can avoid setting up custom visualization filters in ParaView. I've also reduced the total time of MixMotorSliding speeding up the total process a bit though you can use your already generated data.

**Comment by lamsoa729** [comment]
We just discovered the parameter files in the Example directory where using an old definition of sylinderColBuf. This has been changed and has resulted in a large (~100x) speed up for DenseStrainingMotion and DenseMonoLayer examples. If you would like to continue testing these systems, please pull the latest main branch for better performance.
